### PR TITLE
Basic git commands

### PR DESCRIPTION
**Pull request by maverik1003**

### CODE REVIEW

**Comment by tryguba** [comment]
great work!

**Review by merry-granger — COMMENTED** [review]
godd work

**Comment by Yevhen96** [comment]
good

**Review by Yevhen96 — APPROVED** [review]

**Review by merry-granger — COMMENTED** [review]
good work

**Review by merry-granger — APPROVED** [review]

**Review by Evan-Kork — APPROVED** [review]

**Pull request merged**
